[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-gemini-fastapi"
version = "0.1.0"
description = "Sistema RAG modular usando FastAPI, ChromaDB y Gemini 3.5 Flash Lite"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "chromadb",
    "google-genai",
    "pydantic",
    "python-dotenv",
    "pymupdf"
]


